name: Build and deploy Node.js app to Azure Web App - rainfallanalysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: Add Python to PATH
        run: |
         sudo apt-get update
         sudo apt-get install -y python3
         export PATH="$PATH:/usr/bin/python3"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          pip3 install numpy meteostat pymongo scikit-learn

      - name: Install npm packages, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Add requirements.txt to artifact
        run: |
         pip install -r requirements.txt
         zip -r release.zip requirements.txt
        working-directory: ${{ github.workspace }}

        
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: ${{ github.workspace }}

      - name: List contents of the zip file
        run: unzip -l release.zip
        working-directory: ${{ github.workspace }}


      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip
          include: |
            ./*
            !.git*
            !node_modules*

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Install Python and Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y python3

      - name: Install Python libraries
        run: |
          python3 -m pip install -r requirements.txt  

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rainfallanalysis'
          slot-name: 'Production'
          package: .





          
