name: Build and deploy Node.js app to Azure Web App - rainfallanalysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Choose a Node.js version that suits your project

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3  # Use 'python3' instead of 'python'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREAPPSERVICE_CLIENT_SECRET }}
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANT_ID }}


      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rainfallanalysis'
          slot-name: 'Production'
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: .

          
